package com.ner.landslide.entity;

import com.ner.landslide.entity.enums.AlertSeverity;
import com.ner.landslide.entity.enums.AlertStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

/** An early-warning alert generated by the Alert Decision Engine for a RiskZone. */
@Entity
@Table(name = "alerts", indexes = {
        @Index(name = "idx_alerts_status", columnList = "status"),
        @Index(name = "idx_alerts_zone", columnList = "risk_zone_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "risk_zone_id", nullable = false)
    private RiskZone riskZone;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AlertSeverity severity;

    @Column(nullable = false, length = 200)
    private String title;

    @Column(nullable = false, columnDefinition = "text")
    private String message;

    /** Radius in kilometers considered affected by this alert. */
    @Column(name = "affected_radius")
    private Double affectedRadius;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private AlertStatus status = AlertStatus.ACTIVE;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "resolved_at")
    private Instant resolvedAt;
}
